### PR TITLE
API - Removed forgotten crypto-random-string package

### PR DESCRIPTION
**Pull request by florin-holhos**
The purpose of this PR was to remove crypto-random-string from api/package.json which has been forgotten during upgrades. This package has been replaced with a custom helper function which generates OTPs

---

### Acceptance Criteria:

---

### Checklist:

- [x] Local manual testing conducted

---

### Tests:

---

### CODE REVIEW

**Comment by finlay-jisc** [comment]
Looks fine, should we commit the changed package-lock as well?

**Comment by florin-holhos** [comment]
> Looks fine, should we commit the changed package-lock as well?

it didn't show me any changes to package-lock.json

**Comment by finlay-jisc** [comment]
> > Looks fine, should we commit the changed package-lock as well?
> 
> it didn't show me any changes to package-lock.json

It should - in this branch, crypto-random-string is still in the dependencies of package-lock.json: https://github.com/JiscSD/octopus/blob/b3ecee718e4ca638862bcbf45517bb28beeec81c/api/package-lock.json#L36

And further down: https://github.com/JiscSD/octopus/blob/b3ecee718e4ca638862bcbf45517bb28beeec81c/api/package-lock.json#L17045-L17061

These get removed for me when I run npm install locally with this branch. I can push it if you want

**Comment by florin-holhos** [comment]
> > > Looks fine, should we commit the changed package-lock as well?
> > 
> > 
> > it didn't show me any changes to package-lock.json
> 
> It should - in this branch, crypto-random-string is still in the dependencies of package-lock.json: https://github.com/JiscSD/octopus/blob/b3ecee718e4ca638862bcbf45517bb28beeec81c/api/package-lock.json#L36
> 
> And further down: https://github.com/JiscSD/octopus/blob/b3ecee718e4ca638862bcbf45517bb28beeec81c/api/package-lock.json#L17045-L17061
> 
> These get removed for me when I run npm install locally with this branch. I can push it if you want

managed to generate the package-lock changes after a fresh install

**Review by finlay-jisc — APPROVED** [review]

**Pull request merged**
