### PR TITLE
OCT-607 investigate upgrade to React 18+

### PR DESCRIPTION
**Pull request by florin-holhos**
The purpose of this PR was to investigate the upgrade of React version from 17 to 18.

After upgrading several packages the application seems to work fine, but there are some caveats that might force us to stick with React v17 until the following issues will be solved: 

- react 18 works with next 13, upgrading to next 13 didn't seem to cause major issues other than just some weird warnings when using 'Image' component
image

[Here](https://github.com/vercel/next.js/issues/40762)'s a long discussion on it, but no obvious fix, it just needs repeating width and height in the 'style' props for no reason... This warning only appears for one specific image into the Footer.

- majority of e2e tests are failing because selectors seem to not work properly with React 18 - https://github.com/microsoft/playwright/issues/13845

- cannot run unit tests using enzyme (not sure why we are using enzyme at all) since there's no support for React 18 - https://stackoverflow.com/questions/72029189/does-enzyme-support-react-version-18

- there may be some other issues that I didn't run into, yet.

---

### Acceptance Criteria:

---

### Tests:

---

### CODE REVIEW

**Comment by florin-holhos** [comment]
> react selector bug is supposed to be fixed, [microsoft/playwright#13864](https://github.com/microsoft/playwright/pull/13864)

**Comment by florin-holhos** [comment]
> The purpose of this PR was to investigate the upgrade of React version from 17 to 18.
> 
> After upgrading several packages the application seems to work fine, but there are some caveats that might force us to stick with React v17 until the following issues will be solved:
> 
> * react 18 works with next 13, upgrading to next 13 didn't seem to cause major issues other than just some weird warnings when using 'Image' component
>   image
> 
> [Here](https://github.com/vercel/next.js/issues/40762)'s a long discussion on it, but no obvious fix, it just needs repeating width and height in the 'style' props for no reason... This warning only appears for one specific image into the Footer.
> 
> * majority of e2e tests are failing because selectors seem to not work properly with React 18 - [[BUG] React selectors do not work with React 18 microsoft/playwright#13845](https://github.com/microsoft/playwright/issues/13845)
> * cannot run unit tests using enzyme (not sure why we are using enzyme at all) since there's no support for React 18 - https://stackoverflow.com/questions/72029189/does-enzyme-support-react-version-18
> * there may be some other issues that I didn't run into, yet.
> 
> ### Acceptance Criteria:
> ### Tests:
> ### Screenshots:

Just found another bug related to next 13
After logged in with ORCID, we have a server side logic that redirects the user to /verify page if their email it's not verified.
This page receives an empty object as page props, which is wrong since we pass a few values as props from getServerSideProps.
image

After page reload, the page receives the actual props that have been passed from getServerSideProps function.
image

**Comment by florin-holhos** [comment]
> react selector bug is supposed to be fixed, [microsoft/playwright#13864](https://github.com/microsoft/playwright/pull/13864)

I've tested updating playwright to the latest version and the selectors seem to work fine, but the login fails for new users because of that page props issue described in the previous comment on /verify page

**Comment by karmseveeratjisc** [comment]
done in another task

**Pull request closed without merging**
